/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SRD
 */
public class PanelOrder extends javax.swing.JPanel {

    /**
     * Creates new form order
     */
    public PanelOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hrgnp = new javax.swing.JTextField();
        hrgnu = new javax.swing.JTextField();
        hrgck = new javax.swing.JTextField();
        hrgbbk = new javax.swing.JTextField();
        hrgudg = new javax.swing.JTextField();
        jmnp = new javax.swing.JTextField();
        jmnu = new javax.swing.JTextField();
        jmck = new javax.swing.JTextField();
        jmbbk = new javax.swing.JTextField();
        jmudg = new javax.swing.JTextField();
        stnp = new javax.swing.JTextField();
        stnu = new javax.swing.JTextField();
        stck = new javax.swing.JTextField();
        stbbk = new javax.swing.JTextField();
        stap = new javax.swing.JTextField();
        hrgap = new javax.swing.JTextField();
        jmap = new javax.swing.JTextField();
        studg = new javax.swing.JTextField();
        hrgt = new javax.swing.JTextField();
        stt = new javax.swing.JTextField();
        jmt = new javax.swing.JTextField();
        hrgss = new javax.swing.JTextField();
        jmss = new javax.swing.JTextField();
        stss = new javax.swing.JTextField();
        jmj = new javax.swing.JTextField();
        stj = new javax.swing.JTextField();
        hrgj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        std = new javax.swing.JTextField();
        sttb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        htg = new javax.swing.JButton();
        nm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nk = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sttt = new javax.swing.JTextField();
        rf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jus = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(800, 570));
        setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel5.setPreferredSize(new java.awt.Dimension(900, 700));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Minuman");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel6.setText("Jumlah");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel7.setText("Sub Total");

        hrgnp.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgnp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgnp.setText("5000");
        hrgnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgnpActionPerformed(evt);
            }
        });

        hrgnu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgnu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgnu.setText("4000");
        hrgnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgnuActionPerformed(evt);
            }
        });

        hrgck.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgck.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgck.setText("10000");
        hrgck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgckActionPerformed(evt);
            }
        });

        hrgbbk.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgbbk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgbbk.setText("25000");
        hrgbbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgbbkActionPerformed(evt);
            }
        });

        hrgudg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgudg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgudg.setText("6000");
        hrgudg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgudgActionPerformed(evt);
            }
        });

        jmnp.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmnp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmnp.setText("0");

        jmnu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmnu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmnu.setText("0");

        jmck.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmck.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmck.setText("0");
        jmck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmckActionPerformed(evt);
            }
        });

        jmbbk.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmbbk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmbbk.setText("0");

        jmudg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmudg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmudg.setText("0");

        stnp.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stnp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stnp.setText("0");
        stnp.setEnabled(false);

        stnu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stnu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stnu.setText("0");
        stnu.setEnabled(false);

        stck.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stck.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stck.setText("0");
        stck.setEnabled(false);
        stck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stckActionPerformed(evt);
            }
        });

        stbbk.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stbbk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stbbk.setText("0");
        stbbk.setEnabled(false);

        stap.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stap.setText("0");
        stap.setEnabled(false);

        hrgap.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgap.setText("3000");
        hrgap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgapActionPerformed(evt);
            }
        });

        jmap.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmap.setText("0");

        studg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        studg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        studg.setText("0");
        studg.setEnabled(false);

        hrgt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgt.setText("1000");
        hrgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgtActionPerformed(evt);
            }
        });

        stt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stt.setText("0");
        stt.setEnabled(false);
        stt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sttActionPerformed(evt);
            }
        });

        jmt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmt.setText("0");

        hrgss.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgss.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgss.setText("6000");
        hrgss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgssActionPerformed(evt);
            }
        });

        jmss.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmss.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmss.setText("0");

        stss.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stss.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stss.setText("0");
        stss.setEnabled(false);

        jmj.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jmj.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jmj.setText("0");

        stj.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        stj.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stj.setText("0");
        stj.setEnabled(false);

        hrgj.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        hrgj.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hrgj.setText("8000");
        hrgj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgjActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel8.setText("Total");

        std.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        std.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        std.setText("0");
        std.setEnabled(false);

        sttb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        sttb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sttb.setText("0");
        sttb.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel9.setText("Diskon");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel10.setText("Total Bayar");

        htg.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        htg.setText("HITUNG");
        htg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htgActionPerformed(evt);
            }
        });

        nm.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("Nama");

        nk.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        nk.setText("0");

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("No. Kursi");

        sttt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        sttt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sttt.setText("0");
        sttt.setEnabled(false);

        rf.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        rf.setText("REFRESH");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel1.setText("Cappucinno");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel2.setText("Cappucinno Cincau");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel13.setText("Mochaccino");

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel14.setText("Mocha Latte");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel15.setText("White Coffee");

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel17.setText("Ice Cube");

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel18.setText("Cappucinno Caramel");

        jus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jus.setText("Coffee Milk");

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel20.setText("Air Putih");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hrgap, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(hrgudg)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hrgnp, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(hrgck)
                                    .addComponent(hrgnu, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(hrgbbk)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hrgt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrgss, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrgj, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmnp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmnu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmck, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmbbk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmudg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmss, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jmj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stnu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stnp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stck, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stbbk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stap, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stss, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sttt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sttb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(std, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(htg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrgnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrgck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sttb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stbbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmbbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgbbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(htg)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmudg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgudg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rf)
                    .addComponent(jLabel15))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrgap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(hrgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(hrgss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jus))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        add(jPanel5);
        jPanel5.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void hrgnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgnpActionPerformed

    private void hrgnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgnuActionPerformed

    private void hrgckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgckActionPerformed

    private void hrgbbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgbbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgbbkActionPerformed

    private void hrgudgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgudgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgudgActionPerformed

    private void stckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stckActionPerformed

    private void jmckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmckActionPerformed

    private void hrgapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgapActionPerformed

    private void hrgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgtActionPerformed

    private void hrgssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgssActionPerformed

    private void sttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sttActionPerformed

    private void hrgjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgjActionPerformed

    private void htgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htgActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(hrgnp.getText());
        int jumlah = Integer.parseInt(jmnp.getText());
        stnp.setText(Integer.toString(jumlah * harga));
        
        int harga1 = Integer.parseInt(hrgnu.getText());
        int jumlah1 = Integer.parseInt(jmnu.getText());
        stnu.setText(Integer.toString(jumlah1 * harga1));
        
        int harga2 = Integer.parseInt(hrgck.getText());
        int jumlah2 = Integer.parseInt(jmck.getText());
        stck.setText(Integer.toString(jumlah2 * harga2));
        
        int harga3 = Integer.parseInt(hrgbbk.getText());
        int jumlah3 = Integer.parseInt(jmbbk.getText());
        stbbk.setText(Integer.toString(jumlah3 * harga3));
        
        int harga4 = Integer.parseInt(hrgudg.getText());
        int jumlah4 = Integer.parseInt(jmudg.getText());
        studg.setText(Integer.toString(jumlah4 * harga4));
        
        int harga5 = Integer.parseInt(hrgap.getText());
        int jumlah5 = Integer.parseInt(jmap.getText());
        stap.setText(Integer.toString(jumlah5 * harga5));
        
        int harga6 = Integer.parseInt(hrgt.getText());
        int jumlah6 = Integer.parseInt(jmt.getText());
        stt.setText(Integer.toString(jumlah6 * harga6));
        
        int harga7 = Integer.parseInt(hrgss.getText());
        int jumlah7 = Integer.parseInt(jmss.getText());
        stss.setText(Integer.toString(jumlah7 * harga7));
        
        int harga8 = Integer.parseInt(hrgj.getText());
        int jumlah8 = Integer.parseInt(jmj.getText());
        stj.setText(Integer.toString(jumlah8 * harga8));
        
        //Menghitung total
        int total1 = Integer.parseInt(stnp.getText());
        int total2 = Integer.parseInt(stnu.getText());
        int total3 = Integer.parseInt(stck.getText());
        int total4 = Integer.parseInt(stbbk.getText());
        int total5 = Integer.parseInt(studg.getText());
        int total6 = Integer.parseInt(stap.getText());
        int total7 = Integer.parseInt(stt.getText());
        int total8 = Integer.parseInt(stss.getText());
        int total9 = Integer.parseInt(stj.getText());
        int full = total1 + total2 + total3 + total4 + total5 + total6 + total7 + total8 + total9;
        sttt.setText("Rp." + full + ",00");
        if (full>300000){
            std.setText("20%");
            full = full-(full * 20/100);
            sttb.setText("Rp." + full + ",00");
        
        }else if (full>200000){
            std.setText("10%");
            full = full-(full * 10/100);
            sttb.setText("Rp." + full + ",00");
        }else {
            sttb.setText("Rp." + full + ",00");
        }
        JOptionPane.showMessageDialog(null, "Silahkan Kasih Ini ke Kasir");
    }//GEN-LAST:event_htgActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
        // TODO add your handling code here:
        nm.setText("");
        nk.setText("0");
        jmnp.setText("0");
        jmnu.setText("0");
        jmck.setText("0");
        jmbbk.setText("0");
        jmudg.setText("0");
        jmap.setText("0");
        jmt.setText("0");
        jmss.setText("0");
        jmj.setText("0");
        stnp.setText("0");
        stnu.setText("0");
        stck.setText("0");
        stbbk.setText("0");
        studg.setText("0");
        stap.setText("0");
        stt.setText("0");
        stss.setText("0");
        stj.setText("0");
        sttt.setText("0");
        std.setText("0");
        sttb.setText("0");
    }//GEN-LAST:event_rfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hrgap;
    private javax.swing.JTextField hrgbbk;
    private javax.swing.JTextField hrgck;
    private javax.swing.JTextField hrgj;
    private javax.swing.JTextField hrgnp;
    private javax.swing.JTextField hrgnu;
    private javax.swing.JTextField hrgss;
    private javax.swing.JTextField hrgt;
    private javax.swing.JTextField hrgudg;
    private javax.swing.JButton htg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jmap;
    private javax.swing.JTextField jmbbk;
    private javax.swing.JTextField jmck;
    private javax.swing.JTextField jmj;
    private javax.swing.JTextField jmnp;
    private javax.swing.JTextField jmnu;
    private javax.swing.JTextField jmss;
    private javax.swing.JTextField jmt;
    private javax.swing.JTextField jmudg;
    private javax.swing.JLabel jus;
    private javax.swing.JTextField nk;
    private javax.swing.JTextField nm;
    private javax.swing.JButton rf;
    private javax.swing.JTextField stap;
    private javax.swing.JTextField stbbk;
    private javax.swing.JTextField stck;
    private javax.swing.JTextField std;
    private javax.swing.JTextField stj;
    private javax.swing.JTextField stnp;
    private javax.swing.JTextField stnu;
    private javax.swing.JTextField stss;
    private javax.swing.JTextField stt;
    private javax.swing.JTextField sttb;
    private javax.swing.JTextField sttt;
    private javax.swing.JTextField studg;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
